FROM node:20

ENV NEXT_PUBLIC_SUPABASE_URL="YOUR_SUPABASE_URL"
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY="YOUR_ANON_KEY"
ENV SUPABASE_SERVICE_ROLE_KEY="YOUR_SERVICE_KEY"
ENV NEXT_PUBLIC_LOGFLARE_API_TOKEN="YOUR_LOGFLARE_API_TOKEN"
ENV NEXT_PUBLIC_LOGFLARE_CLIENT_TOKEN="YOUR_LOGFLARE_CLIENT_TOKEN"
ENV SMTP_HOST="YOUR_SMTP_HOST"
ENV SMTP_PORT="YOUR_SMTP_PORT"
ENV SMTP_USER="YOUR_SMTP_USER"
ENV SMTP_PASSWORD="YOUR_PASSWORD"

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
